[package]
name = "esp-home-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = [
  "critical-section",
  "embassy-time-driver",
  "embassy-sync",
] }
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
esp-idf-hal = "0.46.2"
embedded-svc = "0.29.0"
anyhow = "1.0.103"
json = "0.12.4"
strum_macros = "0.28.0"
urlencoding = "2.1.3"
thiserror = "2.0.20"
num-traits = "0.2.19"
embedded-hal = "0.2"
onewire = "0.4.0"
critical-section = "1.0"

[build-dependencies]
minify-html = "0.18.1"
